[package]
name = "java-v1_19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minecraft_data = { path = "../../common" }
bytes="1.1.0"
uuid = "1.1.2"